import * as yup from 'yup';

export const validationSchema = yup.object().shape({
  kursus_ID: yup.string().required('Kursus Wajib Dipilih'),
  nisn: yup.number().required('NISN Wajib Diisi'),
  nis: yup.number().required('NIS Wajib Diisi'),
  nik: yup.number().required('NIK Wajib Diisi'),
  nama_lengkap: yup.string().required('Nama Lengkap Wajib Diisi'),
  jenis_kelamin: yup.string().required('Jenis Kelamin Wajib Dipilih'),
  pas_foto: yup.string().required('Pas Foto Wajib Diisi'),
  tempat_lahir: yup.string().required('Tempat Lahir Wajib Diisi'),
  tanggal_lahir: yup.string().required('Tanggal Lahir Wajib Diisi'),
  agama_ID: yup.string().required('Agama Wajib Dipilih'),
  email: yup.string().email().required('Email Wajib Diisi'),
  no_telepon: yup.string().required('No Telepon Wajib Diisi'),
  alamat: yup.string().required('Alamat Wajib Diisi'),
  nama_ayah: yup.string().required('Nama Ayah Wajib Diisi'),
  pekerjaan_ayah_ID: yup.string().required('Pekerjaan Ayah Wajib Dipilih'),
  no_telepon_ayah: yup.string().required('No Telepon Ayah Wajib Diisi'),
  pendidikan_ayah_ID: yup.string().required('Pendidikan Ayah Wajib Dipilih'),
  penghasilan_ayah_ID: yup.string().required('Penghasilan Ayah Wajib Dipilih'),
  nama_ibu: yup.string().required('Nama Ibu Wajib Diisi'),
  pekerjaan_ibu_ID: yup.string().required('Pekerjaan Ibu Wajib Dipih'),
  no_telepon_ibu: yup.string().required('No Telepon Ibu Wajib Diisi'),
  pendidikan_ibu_ID: yup.string().required('Pendididikan Ibu Wajib Dipilih'),
  penghasilan_ibu_ID: yup.string().required('Penghasilan Ibu Wajib Dipilih'),
  slip_gaji_ayah_ibu: yup.string().required('Slip Gaji Ayah Ibu Wajib Diisi'),
  foto_kk: yup.string().required('Foto KK Wajib Diisi'),
  sekolah_ID: yup.string().required('Sekolah Wajib Dipilih'),
  nilai_semester_1: yup.number().required('Nilai Semester 1 Wajib Diisi'),
  nilai_semester_2: yup.number().required('Nilai Semester 2 Wajib Diisi'),
  nilai_semester_3: yup.number().required('Nilai Semester 3 Wajib Diisi'),
  nilai_semester_4: yup.number().required('Nilai Semester 4 Wajib Diisi'),
  nilai_semester_5: yup.number().optional(),
  nilai_semester_6: yup.number().optional(),
  raport: yup.string().required('Raport Wajib Diisi'),
  prestasi: yup.string().optional(),
});
